"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-06-29 16:42:35.595322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binary_resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('content_length', sa.BigInteger(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('part_masters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('standard_part', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'number', name='uq_part_master_ws_number')
    )
    op.create_table('part_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('part_master_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checkout_user_id', sa.Uuid(), nullable=True),
    sa.Column('checkout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by_id', sa.Uuid(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('obsoleted_by_id', sa.Uuid(), nullable=True),
    sa.Column('obsoleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('WIP','RELEASED','OBSOLETE')", name='ck_part_revision_status'),
    sa.ForeignKeyConstraint(['checkout_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['obsoleted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['part_master_id'], ['part_masters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_master_id', 'version', name='uq_part_revision_master_version')
    )
    op.create_table('part_iterations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('part_revision_id', sa.Uuid(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('iteration_note', sa.Text(), nullable=True),
    sa.Column('native_cad_file_id', sa.Uuid(), nullable=True),
    sa.Column('check_in_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('iteration > 0', name='ck_part_iteration_positive'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['native_cad_file_id'], ['binary_resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_revision_id'], ['part_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_revision_id', 'iteration', name='uq_part_iteration_revision_iter')
    )
    op.create_table('geometries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iteration_id', sa.Uuid(), nullable=False),
    sa.Column('binary_resource_id', sa.Uuid(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('x_min', sa.Double(), nullable=False),
    sa.Column('y_min', sa.Double(), nullable=False),
    sa.Column('z_min', sa.Double(), nullable=False),
    sa.Column('x_max', sa.Double(), nullable=False),
    sa.Column('y_max', sa.Double(), nullable=False),
    sa.Column('z_max', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['binary_resource_id'], ['binary_resources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['iteration_id'], ['part_iterations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_usage_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_iteration_id', sa.Uuid(), nullable=False),
    sa.Column('component_master_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Double(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['component_master_id'], ['part_masters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_iteration_id'], ['part_iterations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cad_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usage_link_id', sa.Uuid(), nullable=False),
    sa.Column('tx', sa.Double(), nullable=False),
    sa.Column('ty', sa.Double(), nullable=False),
    sa.Column('tz', sa.Double(), nullable=False),
    sa.Column('rotation_type', sa.String(length=10), nullable=False),
    sa.Column('rx', sa.Double(), nullable=True),
    sa.Column('ry', sa.Double(), nullable=True),
    sa.Column('rz', sa.Double(), nullable=True),
    sa.Column('m00', sa.Double(), nullable=True),
    sa.Column('m01', sa.Double(), nullable=True),
    sa.Column('m02', sa.Double(), nullable=True),
    sa.Column('m10', sa.Double(), nullable=True),
    sa.Column('m11', sa.Double(), nullable=True),
    sa.Column('m12', sa.Double(), nullable=True),
    sa.Column('m20', sa.Double(), nullable=True),
    sa.Column('m21', sa.Double(), nullable=True),
    sa.Column('m22', sa.Double(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.CheckConstraint("rotation_type IN ('ANGLE','MATRIX')", name='ck_cad_instance_rotation_type'),
    sa.ForeignKeyConstraint(['usage_link_id'], ['part_usage_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # 查询索引（autogenerate 不会生成这些非约束索引，手工补齐，见 data-model.md §五）
    op.create_index("idx_part_masters_workspace", "part_masters", ["workspace_id"])
    op.create_index("idx_part_masters_number", "part_masters", ["number"])
    op.create_index("idx_part_revisions_master", "part_revisions", ["part_master_id"])
    op.create_index("idx_part_revisions_checkout", "part_revisions", ["checkout_user_id"])
    op.create_index("idx_part_revisions_status", "part_revisions", ["status"])
    op.create_index("idx_part_iterations_revision", "part_iterations", ["part_revision_id"])
    op.create_index("idx_geometries_iteration", "geometries", ["iteration_id"])
    op.create_index("idx_part_usage_links_parent", "part_usage_links", ["parent_iteration_id"])
    op.create_index("idx_part_usage_links_component", "part_usage_links", ["component_master_id"])
    op.create_index("idx_cad_instances_usage_link", "cad_instances", ["usage_link_id"])

    # 默认工作空间种子（供 users.workspace_id 引用；admin 用户留待 M1.5 认证计划）
    op.execute(
        "INSERT INTO workspaces (id, name, description, created_at, updated_at) "
        "VALUES ('00000000-0000-0000-0000-000000000001', 'default', '默认工作空间', now(), now())"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_cad_instances_usage_link", table_name="cad_instances")
    op.drop_index("idx_part_usage_links_component", table_name="part_usage_links")
    op.drop_index("idx_part_usage_links_parent", table_name="part_usage_links")
    op.drop_index("idx_geometries_iteration", table_name="geometries")
    op.drop_index("idx_part_iterations_revision", table_name="part_iterations")
    op.drop_index("idx_part_revisions_status", table_name="part_revisions")
    op.drop_index("idx_part_revisions_checkout", table_name="part_revisions")
    op.drop_index("idx_part_revisions_master", table_name="part_revisions")
    op.drop_index("idx_part_masters_number", table_name="part_masters")
    op.drop_index("idx_part_masters_workspace", table_name="part_masters")
    op.drop_table('cad_instances')
    op.drop_table('part_usage_links')
    op.drop_table('geometries')
    op.drop_table('part_iterations')
    op.drop_table('part_revisions')
    op.drop_table('part_masters')
    op.drop_table('users')
    op.drop_table('workspaces')
    op.drop_table('binary_resources')
    # ### end Alembic commands ###
