"""config

Revision ID: 2340ae396ad8
Revises: 43d78656c87c
Create Date: 2026-06-30 16:27:01.355674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2340ae396ad8'
down_revision: Union[str, None] = '43d78656c87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spec', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('document_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('configuration_item_children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['configuration_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['configuration_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', name='uix_config_child')
    )
    op.create_table('configuration_item_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('configuration_item_id', sa.UUID(), nullable=False),
    sa.Column('part_type', sa.String(length=16), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['configuration_item_id'], ['configuration_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('configuration_item_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('effectivity_start', sa.String(length=32), nullable=True),
    sa.Column('effectivity_end', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_mode', sa.String(length=8), nullable=False),
    sa.Column('cc_users', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['configuration_item_id'], ['configuration_items.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('configuration_profile_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('source_config_item_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_config_item_id'], ['configuration_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_review_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_status_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('operator_name', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_working_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('source_config_item_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_config_item_id'], ['configuration_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eco_number', sa.String(length=32), nullable=False),
    sa.Column('ecr_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_mode', sa.String(length=8), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('document_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cc_users', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('release_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frozen_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ecr_id'], ['ecrs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eco_number')
    )
    op.create_table('eco_execution_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eco_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('affected_item_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_code', sa.String(length=64), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('entity_version', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_entity_id', sa.UUID(), nullable=True),
    sa.Column('new_version', sa.String(length=32), nullable=True),
    sa.Column('parent_entity_id', sa.UUID(), nullable=True),
    sa.Column('parent_new_entity_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affected_item_id'], ['ecr_affected_items.id'], ),
    sa.ForeignKeyConstraint(['eco_id'], ['ecos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eco_review_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eco_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['eco_id'], ['ecos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eco_status_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eco_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('operator_name', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['eco_id'], ['ecos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eco_status_logs')
    op.drop_table('eco_review_records')
    op.drop_table('eco_execution_items')
    op.drop_table('ecos')
    op.drop_table('configuration_working_items')
    op.drop_table('configuration_status_logs')
    op.drop_table('configuration_review_records')
    op.drop_table('configuration_profile_items')
    op.drop_table('configuration_profiles')
    op.drop_table('configuration_item_parts')
    op.drop_table('configuration_item_children')
    op.drop_table('configuration_items')
    # ### end Alembic commands ###
