"""add_inventory_tables

Revision ID: 43d78656c87c
Revises: 76fc4de22ebe
Create Date: 2026-06-30 16:25:30.864085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43d78656c87c'
down_revision: Union[str, None] = '76fc4de22ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(length=16), nullable=True),
    sa.Column('doc_number', sa.String(length=32), nullable=True),
    sa.Column('doc_line_id', sa.UUID(), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('operator_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spec', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('ref_entity_type', sa.String(length=16), nullable=True),
    sa.Column('ref_entity_id', sa.UUID(), nullable=True),
    sa.Column('track_mode', sa.String(length=16), nullable=False),
    sa.Column('safety_stock', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('default_keeper_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_keeper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_number', sa.String(length=32), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('biz_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('to_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('reviewers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_mode', sa.String(length=8), nullable=False),
    sa.Column('keeper_id', sa.UUID(), nullable=True),
    sa.Column('keeper_name', sa.String(length=64), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('document_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['keeper_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_number')
    )
    op.create_table('inventory_stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['inventory_materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'warehouse_id', 'batch_no', name='uix_stock_mat_wh_batch')
    )
    op.create_table('inventory_document_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=True),
    sa.Column('book_quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('counted_quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['inventory_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['inventory_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_review_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['inventory_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_status_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('operator_name', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['inventory_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_status_logs')
    op.drop_table('inventory_review_records')
    op.drop_table('inventory_document_lines')
    op.drop_table('inventory_stock')
    op.drop_table('inventory_documents')
    op.drop_table('warehouses')
    op.drop_table('inventory_materials')
    op.drop_table('inventory_ledger')
    # ### end Alembic commands ###
