"""add_change_issues

Revision ID: b4b83b14d522
Revises: 566ea1d2c5de
Create Date: 2026-07-01 15:06:40.363264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4b83b14d522'
down_revision: Union[str, None] = '566ea1d2c5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_number', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('initiator', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cc_users', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_number')
    )
    op.add_column('ecrs', sa.Column('issue_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ecrs', 'change_issues', ['issue_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ecrs', type_='foreignkey')
    op.drop_column('ecrs', 'issue_id')
    op.drop_table('change_issues')
    # ### end Alembic commands ###
