"""add_iteration_id_to_part_attachments

Revision ID: dc37a01938c6
Revises: 6a090d6571b1
Create Date: 2026-07-03 18:38:06.328797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc37a01938c6'
down_revision: Union[str, None] = '6a090d6571b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_attachments', sa.Column('iteration_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'part_attachments', 'part_iterations', ['iteration_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'part_attachments', type_='foreignkey')
    op.drop_column('part_attachments', 'iteration_id')
    # ### end Alembic commands ###
